spring:
  application:
    name: coursehub
  datasource:
    url: jdbc:mysql://localhost:3304/course_hub
    username: root
    password: 123456a@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: nam.pd193034@gmail.com
    password: vnhv azat dtew uwth
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
